version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions-updates:
        patterns:
          - "actions/checkout"
          - "actions/upload-artifact"
          - "gitleaks/gitleaks-action"
    ignore:
      - dependency-name: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml"

  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      uv-version-updates:
        patterns: ["*"]