-- Cinema City PostgreSQL schema snapshot.
-- Generated from Alembic migrations. Do not edit this file manually.
-- Revision ID: 20260828_0001

BEGIN;

CREATE TABLE alembic_version (
    version_num VARCHAR(32) NOT NULL,
    CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
);

CREATE TABLE cinemas (
    cinema_id SERIAL NOT NULL,
    name VARCHAR(200) NOT NULL,
    CONSTRAINT pk_cinemas PRIMARY KEY (cinema_id)
);

CREATE TABLE movies (
    movie_id SERIAL NOT NULL,
    title VARCHAR(200) NOT NULL,
    duration_minutes INTEGER NOT NULL,
    description VARCHAR(300) NOT NULL,
    genre VARCHAR(30) NOT NULL,
    ticket_price INTEGER NOT NULL,
    CONSTRAINT pk_movies PRIMARY KEY (movie_id),
    CONSTRAINT ck_movies_duration_minutes_range
        CHECK (duration_minutes BETWEEN 1 AND 240),
    CONSTRAINT ck_movies_ticket_price_range
        CHECK (ticket_price BETWEEN 1 AND 99),
    CONSTRAINT uq_movies_title UNIQUE (title)
);

CREATE TABLE users (
    user_id SERIAL NOT NULL,
    auth_provider VARCHAR(50) NOT NULL,
    auth_subject VARCHAR(255) NOT NULL,
    full_name VARCHAR(200) NOT NULL,
    phone_number VARCHAR(30),
    email VARCHAR(320),
    CONSTRAINT pk_users PRIMARY KEY (user_id),
    CONSTRAINT uq_users_auth_provider_auth_subject
        UNIQUE (auth_provider, auth_subject),
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT uq_users_phone_number UNIQUE (phone_number)
);

CREATE TABLE halls (
    hall_id SERIAL NOT NULL,
    cinema_id INTEGER NOT NULL,
    hall_name VARCHAR(100) NOT NULL,
    CONSTRAINT pk_halls PRIMARY KEY (hall_id),
    CONSTRAINT fk_halls_cinema_id_cinemas
        FOREIGN KEY(cinema_id) REFERENCES cinemas (cinema_id)
);

CREATE TABLE seats (
    seat_id SERIAL NOT NULL,
    hall_id INTEGER NOT NULL,
    row_number INTEGER NOT NULL,
    seat_number INTEGER NOT NULL,
    CONSTRAINT pk_seats PRIMARY KEY (seat_id),
    CONSTRAINT ck_seats_row_number_positive CHECK (row_number > 0),
    CONSTRAINT ck_seats_seat_number_positive CHECK (seat_number > 0),
    CONSTRAINT fk_seats_hall_id_halls
        FOREIGN KEY(hall_id) REFERENCES halls (hall_id),
    CONSTRAINT uq_seats_hall_id_row_number_seat_number
        UNIQUE (hall_id, row_number, seat_number)
);

CREATE TABLE shows (
    show_id SERIAL NOT NULL,
    movie_id INTEGER NOT NULL,
    hall_id INTEGER NOT NULL,
    start_time VARCHAR(64) NOT NULL,
    ticket_price INTEGER NOT NULL,
    CONSTRAINT pk_shows PRIMARY KEY (show_id),
    CONSTRAINT ck_shows_ticket_price_range
        CHECK (ticket_price BETWEEN 1 AND 99),
    CONSTRAINT fk_shows_hall_id_halls
        FOREIGN KEY(hall_id) REFERENCES halls (hall_id),
    CONSTRAINT fk_shows_movie_id_movies
        FOREIGN KEY(movie_id) REFERENCES movies (movie_id)
);

CREATE TABLE bookings (
    booking_id SERIAL NOT NULL,
    user_id INTEGER NOT NULL,
    show_id INTEGER NOT NULL,
    CONSTRAINT pk_bookings PRIMARY KEY (booking_id),
    CONSTRAINT fk_bookings_show_id_shows
        FOREIGN KEY(show_id) REFERENCES shows (show_id),
    CONSTRAINT fk_bookings_user_id_users
        FOREIGN KEY(user_id) REFERENCES users (user_id)
);

CREATE TABLE booking_seats (
    booking_id INTEGER NOT NULL,
    show_id INTEGER NOT NULL,
    seat_id INTEGER NOT NULL,
    CONSTRAINT fk_booking_seats_booking_id_bookings
        FOREIGN KEY(booking_id) REFERENCES bookings (booking_id) ON DELETE CASCADE,
    CONSTRAINT fk_booking_seats_seat_id_seats
        FOREIGN KEY(seat_id) REFERENCES seats (seat_id),
    CONSTRAINT fk_booking_seats_show_id_shows
        FOREIGN KEY(show_id) REFERENCES shows (show_id),
    CONSTRAINT uq_booking_seats_booking_id_seat_id
        UNIQUE (booking_id, seat_id),
    CONSTRAINT uq_booking_seats_show_id_seat_id
        UNIQUE (show_id, seat_id)
);

INSERT INTO alembic_version (version_num) VALUES ('20260828_0001');

COMMIT;
