name: Lint GitHub Actions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  actionlint:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@3d3c42e2a4cd39634e7ca3046f41e57c631b191a # v7.0.1

      - name: Run actionlint
        uses: rhysd/actionlint-action@7374cbaf0f3299723528b8cf442fb83501a40306 # v1.11.1